.TH WARMUX-SERVER 6 "October 05, 2010"
.SH NAME
warmux\-server \- WarMUX server
.SH SYNOPSIS
.PP
\fBwarmux\-server\fR [\-f \fIconfigfile\fP]
.SH DESCRIPTION
.PP
warmux\-server is the dedicated server for the WarMUX game.
.SH AUTHOR
This manual page was written by Felix Geyer <debfx-pkg@fobos.de> for the Debian
project (but may be used by others). Permission is granted to copy, distribute
and/or modify this document under the terms of the GNU General Public License,
Version 2 any later version published by the Free Software Foundation.
